[project]
name = "solve-earn"
description = "Decentralized bug bounty platform"
authors = []
telemetry = false
cache_dir = "./.cache"
requirements = []

[repl]
epoch = "3.0"

[contracts.reputation]
path = "contracts/reputation.clar"

[contracts.bounty-vault]
path = "contracts/bounty-vault.clar"
depends_on = ["reputation", "dispute-resolver"]

[contracts.dispute-resolver]
path = "contracts/dispute-resolver.clar"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
