#!/bin/bash

# Mainnet Contract Testing Script
# This script performs test transactions on your deployed Solve-Earn contracts

CONTRACT_ADDRESS="SP31PKQVQZVZCK3FM3NH67CGD6G1FMR17VQVS2W5T"
NETWORK="mainnet"

echo "🚀 Testing Solve-Earn Contracts on Mainnet"
echo "Contract Address: $CONTRACT_ADDRESS"
echo "==========================================="
echo ""

# Color codes for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Test 1: Register as a Researcher
echo -e "${YELLOW}Test 1: Register as a Researcher${NC}"
echo "Contract: reputation"
echo "Function: register-researcher"
echo ""
echo "Run this command in your Stacks wallet or via CLI:"
echo "stx call-contract $CONTRACT_ADDRESS reputation register-researcher --network $NETWORK"
echo ""
echo "Expected Result: Transaction success, researcher profile created"
echo "==========================================="
echo ""

# Test 2: Create a Bounty Program
echo -e "${YELLOW}Test 2: Create a Bug Bounty Program${NC}"
echo "Contract: bounty-vault"
echo "Function: create-bounty"
echo ""
echo "Parameters:"
echo "  - title: \"Test API Security Audit\""
echo "  - description: \"Find vulnerabilities in our REST API\""
echo "  - total-pool: 100000000 (100 STX in microSTX)"
echo "  - critical-reward: 50000000 (50 STX)"
echo "  - high-reward: 30000000 (30 STX)"
echo "  - medium-reward: 15000000 (15 STX)"
echo "  - low-reward: 5000000 (5 STX)"
echo "  - duration-blocks: 4320 (approximately 30 days)"
echo ""
echo "Run this command:"
echo "stx call-contract $CONTRACT_ADDRESS bounty-vault create-bounty \\"
echo "  '\"Test API Security Audit\"' \\"
echo "  '\"Find vulnerabilities in our REST API\"' \\"
echo "  100000000 50000000 30000000 15000000 5000000 4320 \\"
echo "  --network $NETWORK"
echo ""
echo "Expected Result: Transaction success, bounty created with ID 1"
echo "==========================================="
echo ""

# Test 3: Check Bounty Details (Read-Only)
echo -e "${YELLOW}Test 3: Read Bounty Details${NC}"
echo "Contract: bounty-vault"
echo "Function: get-bounty (read-only)"
echo ""
echo "Run this command:"
echo "stx call-contract-func $CONTRACT_ADDRESS bounty-vault get-bounty 1 \\"
echo "  --network $NETWORK --read-only"
echo ""
echo "Expected Result: Returns bounty details including pool, rewards, and status"
echo "==========================================="
echo ""

# Test 4: Submit a Vulnerability
echo -e "${YELLOW}Test 4: Submit a Vulnerability Report${NC}"
echo "Contract: bounty-vault"
echo "Function: submit-vulnerability"
echo ""
echo "Parameters:"
echo "  - bounty-id: 1"
echo "  - severity: \"high\""
echo "  - report-hash: 0x1234567890abcdef1234567890abcdef12345678 (32 bytes)"
echo ""
echo "Run this command:"
echo "stx call-contract $CONTRACT_ADDRESS bounty-vault submit-vulnerability \\"
echo "  1 '\"high\"' 0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef \\"
echo "  --network $NETWORK"
echo ""
echo "Expected Result: Transaction success, submission created with ID 1"
echo "==========================================="
echo ""

# Test 5: Check Submission Details (Read-Only)
echo -e "${YELLOW}Test 5: Read Submission Details${NC}"
echo "Contract: bounty-vault"
echo "Function: get-submission (read-only)"
echo ""
echo "Run this command:"
echo "stx call-contract-func $CONTRACT_ADDRESS bounty-vault get-submission 1 \\"
echo "  --network $NETWORK --read-only"
echo ""
echo "Expected Result: Returns submission details including status and reward"
echo "==========================================="
echo ""

# Test 6: Approve a Submission (Contract Owner Only)
echo -e "${YELLOW}Test 6: Approve a Submission${NC}"
echo "Contract: bounty-vault"
echo "Function: approve-submission"
echo "Note: Only the bounty creator can approve submissions"
echo ""
echo "Parameters:"
echo "  - submission-id: 1"
echo ""
echo "Run this command (from bounty creator wallet):"
echo "stx call-contract $CONTRACT_ADDRESS bounty-vault approve-submission \\"
echo "  1 --network $NETWORK"
echo ""
echo "Expected Result: Transaction success, reward transferred to researcher"
echo "==========================================="
echo ""

# Test 7: Check Researcher Profile (Read-Only)
echo -e "${YELLOW}Test 7: Read Researcher Profile${NC}"
echo "Contract: reputation"
echo "Function: get-researcher-profile (read-only)"
echo ""
echo "Run this command (replace YOUR_ADDRESS with your Stacks address):"
echo "stx call-contract-func $CONTRACT_ADDRESS reputation get-researcher-profile \\"
echo "  'YOUR_ADDRESS' --network $NETWORK --read-only"
echo ""
echo "Expected Result: Returns profile with submissions, earnings, and reputation"
echo "==========================================="
echo ""

# Test 8: Check Reputation Score (Read-Only)
echo -e "${YELLOW}Test 8: Check Reputation Score${NC}"
echo "Contract: reputation"
echo "Function: get-reputation-score (read-only)"
echo ""
echo "Run this command (replace YOUR_ADDRESS with your Stacks address):"
echo "stx call-contract-func $CONTRACT_ADDRESS reputation get-reputation-score \\"
echo "  'YOUR_ADDRESS' --network $NETWORK --read-only"
echo ""
echo "Expected Result: Returns reputation score (0-100)"
echo "==========================================="
echo ""

# Test 9: Get Total Bounties (Read-Only)
echo -e "${YELLOW}Test 9: Get Total Bounties${NC}"
echo "Contract: bounty-vault"
echo "Function: get-total-bounties (read-only)"
echo ""
echo "Run this command:"
echo "stx call-contract-func $CONTRACT_ADDRESS bounty-vault get-total-bounties \\"
echo "  --network $NETWORK --read-only"
echo ""
echo "Expected Result: Returns total number of bounties created"
echo "==========================================="
echo ""

# Test 10: Register as Arbiter
echo -e "${YELLOW}Test 10: Register as Arbiter${NC}"
echo "Contract: dispute-resolver"
echo "Function: register-arbiter"
echo ""
echo "Run this command:"
echo "stx call-contract $CONTRACT_ADDRESS dispute-resolver register-arbiter \\"
echo "  --network $NETWORK"
echo ""
echo "Expected Result: Transaction success, registered as dispute arbiter"
echo "==========================================="
echo ""

echo ""
echo -e "${GREEN}✅ All test scenarios documented!${NC}"
echo ""
echo "📝 Notes:"
echo "  - Make sure you have STX in your wallet for transaction fees"
echo "  - For create-bounty, you need enough STX for the total pool amount"
echo "  - Read-only functions don't require transaction fees"
echo "  - Wait for transactions to confirm before running dependent tests"
echo ""
echo "🔍 To check transaction status:"
echo "  Visit: https://explorer.hiro.so/txid/<YOUR_TXID>?chain=mainnet"
echo ""
echo "💡 Alternative: Use the frontend at your deployed URL"
echo "  The UI provides a better experience for testing all functions"
echo ""
